### ISSUE TITLE
告警恢复的value不变怎么解决

### ISSUE THREAD

**Issue by shizy123** [timonwong/prometheus-webhook-dingtalk#101]
[FIRING:1] 
[触发告警] 容器pod: filebeat-xjtxp CPU单核大于10%
级别: WARNING
值: 30.04977812679487%
测试环境k8s-WARNING告警
[RESOLVED] 
[告警恢复] 容器pod: filebeat-xjtxp CPU单核大于10%
级别: WARNING
值: 30.04977812679487%
触发告警是30%，但是[RESOLVED] 恢复还是30%，这个怎么解决？
我自定义的取值应该是没有问题的> 值: {{ .Annotations.value }}

**Comment by timonwong** [comment]
这个是由于 prometheus 自身限制，参考这里的讨论:
https://github.com/timonwong/prometheus-webhook-dingtalk/issues/17#issuecomment-419023930
