### ISSUE TITLE
返回 404 

### ISSUE THREAD

**Issue by xuejipeng** [timonwong/prometheus-webhook-dingtalk#12]
prometheus-webhook-dingtalk 报错如下
evel=info ts=2018-05-14T05:46:51.050254532Z caller=entry.go:22 http_scheme=http http_proto=HTTP/1.1 http_method=POST remote_addr=127.0.0.1:41260 user_agent=Alertmanager/0.14.0 uri=http://localhost:8060/dingtalk/webhook1/send resp_status=404 resp_bytes_length=19 resp_elasped_ms=0.078093 msg="request complete"

请问这是怎么回事

**Comment by xuejipeng** [comment]
我用本地的方式使用时没问题的，放在 k8s 环境中，把它和alertmanager 放在同一个pod 上就会报这个错误

**Comment by timonwong** [comment]
参数加了引号吧，k8s 中 args 不是 shell 处理的，不能加引号

**Comment by xuejipeng** [comment]
嗯呢 去掉引号就好了👍👍👍👍👍👍👍

**Comment by xuejipeng** [comment]
可以再问您个问题么？我用 alertmanager 发邮件报警的时候出现下面这个错误
level=debug ts=2018-05-14T11:12:40.877341291Z caller=notify.go:605 component=dispatcher msg="Notify attempt failed" attempt=2 integration=email receiver=email err=EOF

**Comment by timonwong** [comment]
> 可以再问您个问题么？我用 alertmanager 发邮件报警的时候出现下面这个错误
> level=debug ts=2018-05-14T11:12:40.877341291Z caller=notify.go:605 component=dispatcher msg="Notify attempt failed" attempt=2 integration=email receiver=email err=EOF

你这个配置的是 email 的，要使用我这个，你需要用 webhook 的

**Comment by xuejipeng** [comment]
我还想问一下 如果我想把钉钉内的 isAtAll 改成 true ,改怎么配置呢

**Comment by timonwong** [comment]
@xuejipeng 这个分支没有这个功能，有个分支有这个功能 https://github.com/AloneRoad/prometheus-webhook-dingtalk/commit/f45fd776d0029588302a7568f316df526eef8eca

由于我们现在不再用钉钉了，所以这个 repo 更新会慢点，之后我会加上这个功能
