### ISSUE TITLE
说明太过于简单了吧

### ISSUE THREAD

**Issue by mofadeyunduo** [timonwong/prometheus-webhook-dingtalk#121]
我去看代码才知道 怎么实现的 差点配错了
话说那个 template 也太复杂了吧  我反正是看了半天 头疼

而且是不是 为了兼容历史版本 感觉有些代码有些奇怪 我的看法是 不如用 v2

**Comment by rayshen3** [comment]
readme里 连webhook地址说明，怎么配置alertmanager，怎么测试都没，就扔一个配置文件示例

**Comment by williamsmith1** [comment]
没错，连webhook地址调用格式都没写，我都是看之前同事的用法才知道怎么访问8060
