### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by zhangyonghui9527** [timonwong/prometheus-webhook-dingtalk#124]
怎么都无法启动，是不是有bug ? prometheus-webhook-dingtalk, version 0.3.0
root@cnszbpbdpngxp02 Online prometheus-webhook-dingtalk # ./prometheus-webhook-dingtalk --web.listen-address=":8060" --web.enable-ui --config.file="./config.yml" --web.enable-lifecycle --log.format=json
prometheus-webhook-dingtalk: error: unknown long flag '--web.enable-ui', try --help
root@cnszbpbdpngxp02 Online prometheus-webhook-dingtalk # ./prometheus-webhook-dingtalk --web.listen-address=":8060"  --config.file="./config.yml" --web.enable-lifecycle --log.format=json
prometheus-webhook-dingtalk: error: unknown long flag '--config.file', try --help
root@cnszbpbdpngxp02 Online prometheus-webhook-dingtalk # ./prometheus-webhook-dingtalk --web.listen-address=":8060"  --ding.profile="./config.yml" --web.enable-lifecycle --log.format=json
panic: runtime error: index out of range

goroutine 1 [running]:
main.(*dingTalkProfilesValue).Set(0xc4200921a0, 0x7fff53a2b647, 0xc, 0xc, 0xb3c580)
	/go/src/github.com/timonwong/prometheus-webhook-dingtalk/cmd/prometheus-webhook-dingtalk/flag.go:21 +0x292
github.com/timonwong/prometheus-webhook-dingtalk/vendor/gopkg.in/alecthomas/kingpin%2ev2.(*Application).setValues(0xc4200ee000, 0xc420162120, 0x0, 0x0, 0xc420162120, 0xae4fe0, 0xc4201de250)
	/go/src/github.com/timonwong/prometheus-webhook-dingtalk/vendor/gopkg.in/alecthomas/kingpin.v2/app.go:485 +0x406
github.com/timonwong/prometheus-webhook-dingtalk/vendor/gopkg.in/alecthomas/kingpin%2ev2.(*Application).Parse(0xc4200ee000, 0xc420090060, 0x4, 0x4, 0xc420171c78, 0x5b5bd1, 0xc4200ee000, 0xc4201500e1)
	/go/src/github.com/timonwong/prometheus-webhook-dingtalk/vendor/gopkg.in/alecthomas/kingpin.v2/app.go:199 +0xdb
github.com/timonwong/prometheus-webhook-dingtalk/vendor/gopkg.in/alecthomas/kingpin%2ev2.Parse(0xc4201500e1, 0xd5)
	/go/src/github.com/timonwong/prometheus-webhook-dingtalk/vendor/gopkg.in/alecthomas/kingpin.v2/global.go:37 +0x78
main.main()
	/go/src/github.com/timonwong/prometheus-webhook-dingtalk/cmd/prometheus-webhook-dingtalk/main.go:34 +0xed

**Comment by timonwong** [comment]
没有，请使用最新版
