### ISSUE TITLE
请问如何自定义模板

### ISSUE THREAD

**Issue by cerberus43** [timonwong/prometheus-webhook-dingtalk#126]
![image](https://user-images.githubusercontent.com/9128878/106569825-fe783c80-656f-11eb-8d0a-32c7ca268d11.png)
启动时已加载自定义的模板了 但发出来的还是default的 配置文件里也改了

**Comment by KeithTt** [comment]
同问...亲测没反应...

默认模板文件的两行内容，初步看了一下也没看出来引用的哪里。
```yaml
{{ define "ding.link.title" }}{{ template "legacy.title" . }}{{ end }}
{{ define "ding.link.content" }}{{ template "legacy.content" . }}{{ end }}
```

有没有高端玩家来现身说法一下？

**Comment by KeithTt** [comment]
我看到了这个默认模板文件，但是应该需要重新编译

https://github.com/timonwong/prometheus-webhook-dingtalk/blob/master/template/default.tmpl
