### ISSUE TITLE
警报中抓取prometheus页面图片

### ISSUE THREAD

**Issue by marksugar** [timonwong/prometheus-webhook-dingtalk#142]
FYI 

@timonwong  @russellgao @wi1dcard 
是否计划在警报中抓取prometheus页面图片的形式附在告警消息中

thanks

**Comment by wi1dcard** [comment]
我认为这不是该项目应该负责的范畴。建议你了解下 Alertmanager 和 Prometheus 的关系和架构，以便更好地理解该项目的逻辑，以及在整个架构中所处的位置。

当然，我不是该项目的主要维护者，只是一个来自社区的 contributor，所以我无法左右具体走向。

请不要无缘无故 mention 社区成员，提交的 issue 如果有价值自然有开发者关注，谢谢。
