### ISSUE TITLE
模板问题

### ISSUE THREAD

**Issue by Lnsh** [timonwong/prometheus-webhook-dingtalk#15]
模板都有哪些变量呢？ 比如我要发送报警时间改怎么写？谢谢大佬

**Comment by nickle-ye** [comment]
同步 + 1

**Comment by D-PENG** [comment]
同问

**Comment by nickle-ye** [comment]
研究了一下。。其实就是基于go-template的配置:

https://golang.org/pkg/text/template/

另外再看看prometheus.go里相关的data structure就可以了。。

**Comment by StandNorthStar** [comment]
模板不太会弄，我配置的恢复告警值不对~~

**Comment by StandNorthStar** [comment]
问下你们告警恢复的 模板怎么写的，我发现默认的恢复就显示 [RESOLVED]   ，其他啥都没了

**Comment by Ray8587** [comment]
我自定义了标签如下，可参考
{{ define "__subject" }}【AlertManager】{{ end }}
{{ define "__text_list" }}{{ range . }}
{{ range .Labels.SortedPairs }}
{{ if eq .Name "cluster" }}> [集群]: {{ .Value | markdown | html }}{{ end }}
{{ if eq .Name "hostname" }}> [主机]: {{ .Value | markdown | html }}{{ end }}
{{ end }}
{{ range .Annotations.SortedPairs }}
{{ if eq .Name "description" }}> [描述]: {{ .Value | markdown | html }}{{ end }}
{{ end }}
[查看详情]({{ .GeneratorURL }})

{{ end }}{{ end }}

{{ define "ding.link.content" }}
{{ if gt (len .Alerts.Firing) 0 }}#### [{{ .Alerts.Firing | len }}]【Firing】
{{ template "__text_list" .Alerts.Firing }}{{ end }}
{{ if gt (len .Alerts.Resolved) 0 }}#### [{{ .Alerts.Resolved | len }}]【Resolved】
{{ template "__text_list" .Alerts.Resolved }}{{ end }}
{{ end }}

**Comment by redpangzi666** [comment]
如何将 `GeneratorURL` 变成 `https` 格式的，我现在超链接出来都是 `http` 格式的，这样访问是不对的

**Comment by zerlee** [comment]
> 我自定义了标签如下，可参考
> {{ define "__subject" }}【AlertManager】{{ end }}
> {{ define "__text_list" }}{{ range . }}
> {{ range .Labels.SortedPairs }}
> {{ if eq .Name "cluster" }}> [集群]: {{ .Value | markdown | html }}{{ end }}
> {{ if eq .Name "hostname" }}> [主机]: {{ .Value | markdown | html }}{{ end }}
> {{ end }}
> {{ range .Annotations.SortedPairs }}
> {{ if eq .Name "description" }}> [描述]: {{ .Value | markdown | html }}{{ end }}
> {{ end }}
> [查看详情]({{ .GeneratorURL }})
> 
> {{ end }}{{ end }}
> 
> {{ define "ding.link.content" }}
> {{ if gt (len .Alerts.Firing) 0 }}#### [{{ .Alerts.Firing | len }}]【Firing】
> {{ template "__text_list" .Alerts.Firing }}{{ end }}
> {{ if gt (len .Alerts.Resolved) 0 }}#### [{{ .Alerts.Resolved | len }}]【Resolved】
> {{ template "__text_list" .Alerts.Resolved }}{{ end }}
> {{ end }}

你好，请教一下，怎么匹配到一些label后将这些label删掉呢？目前label有点多，想精简一下
<img width="355" alt="7D7FF6CC-6DB3-45d8-9C5F-67E87A83B53C" src="https://user-images.githubusercontent.com/20266664/61704599-a7888900-ad76-11e9-9ab5-9b08875c07fd.png">

比如匹配到namespace，就把这个标签删除。 {{ if eq .Name "namespace" }} 后面应该怎么写？

@whithen

**Comment by timonwong** [comment]
v1.2.0 新增了 web ui，希望能帮到

https://github.com/timonwong/prometheus-webhook-dingtalk/blob/master/docs/FAQ_zh.md

**Comment by baiyibing123** [comment]
> 模板都有哪些变量呢？ 比如我要发送报警时间改怎么写？谢谢大佬

解决了吗
