### ISSUE TITLE
支持多模板？

### ISSUE THREAD

**Issue by nickle-ye** [timonwong/prometheus-webhook-dingtalk#16]
目前看了一下，发觉只可以支持一个模板，请问一下，能不能根据profile级别，对应的定义自己的模板。

因为往往不同的钉钉群，就是不同的业务组，他们可能关注的模板是不一样的。。

所以最好有这样的模板

**Comment by timonwong** [comment]
现阶段我建议开多个这个 instance 解决你的需求, 这个需求会加上
