### ISSUE TITLE
模板告警恢复问题

### ISSUE THREAD

**Issue by StandNorthStar** [timonwong/prometheus-webhook-dingtalk#17]
您好请问下告警恢复这个模板怎么写？
{{ define "__text_alert_list" }}{{ range . }}
{{ range .Annotations.SortedPairs }}> - {{ .Value | markdown | html }}
{{ end }}
{{ end }}{{ end }}
我配置告警恢复还是引用这一段内容，但是告警恢复的时候值是错的，仍然是之前告警值而不是最新恢复值。
想问下这个恢复这段改怎么写或者怎么引用？

**Comment by StandNorthStar** [comment]
{{ define "__subject" }}[{{ if eq .Status "firing" }}告警:{{ .Alerts.Firing | len }}{{ else }}恢复{{ end }}]{{ end }}


{{ define "__text_alert_list" }}
{{ if eq .Status "firing" }}
{{ range .Alerts.Firing }}
{{ range .Annotations.SortedPairs }}> - {{ .Value | markdown | html }}
{{ end }}{{ end }}

{{ else if eq .Status "resolved" }}
{{ range .Alerts.Resolved }}
{{ range .Annotations.SortedPairs }}> - {{ .Value | markdown | html }}
{{ end }}{{ end }}
{{ end }}
{{ end }}

{{ define "__alertmanagerURL" }}{{ end }}
{{ define "ding.link.title" }}{{ template "__subject" . }}{{ end }}
{{ define "ding.link.content" }}#### \[{{ if eq .Status "firing" }}告警:{{ .Alerts.Firing | len }}{{ else }}恢复{{ end }}\]
{{ template "__text_alert_list" . }}
{{ end }}
{{ end }}

**Comment by StandNorthStar** [comment]
楼主，没有恢复值

**Comment by StandNorthStar** [comment]
这个是我输出的告警值和恢复值 ， 这两个是一样的。
[告警:1]
map[description:node exporter down! host:localhost_node_yml summary:当前值：0 instance:192.168.10.107:9100]
node exporter down! host:localhost_node_yml
当前值：0 instance:192.168.10.107:9100
-----------------------------------------------------------------------
[恢复]
map[description:node exporter down! host:localhost_node_yml summary:当前值：0 instance:192.168.10.107:9100]
node exporter down! host:localhost_node_yml
当前值：0 instance:192.168.10.107:9100

**Comment by timonwong** [comment]
Prometheus 就是这样的
See: https://github.com/prometheus/alertmanager/issues/992

**Comment by StandNorthStar** [comment]
额，我还一直以为是自己弄错了~~ 。 谢谢您呀，webhook挺好用 3KS！
