### ISSUE TITLE
作镜像提示没有prometheus-webhook-dingtalk这个目录或文件？

### ISSUE THREAD

**Issue by only21tender** [timonwong/prometheus-webhook-dingtalk#171]
Step 7/17 : COPY .build/${OS}-${ARCH}/cmd/prometheus-webhook-dingtalk   /bin/prometheus-webhook-dingtalk
COPY failed: stat /var/lib/docker/tmp/docker-builder936203033/.build/linux-amd64/prometheus-webhook-dingtalk: no such file or directory

**Comment by timonwong** [comment]
这个 Dockerfile 是 CI 用的

或者 "$(go env GOPATH)/bin/promu" crossbuild，输出 binary artifacts，再 docker build

**Comment by timonwong** [comment]
```
make promu
promu crossbuild -p linux/amd64  # promu 地址可能需要换成 "$(go env GOPATH)/bin/promu" 
make common-docker-amd64
```

**Comment by only21tender** [comment]
感谢，手动传了一个bin文件，稍微改了下dockerfile也一样可以执行的，已解决
