### ISSUE TITLE
kubernetes 下无法使用svc访问接口

### ISSUE THREAD

**Issue by Ghostbaby** [timonwong/prometheus-webhook-dingtalk#18]
+ curl -XPOST '-d{
    "receiver": "admins",
    "status": "firing",
    "alerts": [
        {
            "status": "firing",
            "labels": {
                "alertname": "something_happend",
                "env": "prod",
                "instance": "server01.int:9100",
                "job": "node",
                "service": "prometheus_bot",
                "severity": "warning",
                "supervisor": "runit"
            },
            "annotations": {
                "summary": "Oops, something happend!"
            },
            "startsAt": "2016-04-27T20:46:37.903Z",
            "endsAt": "0001-01-01T00:00:00Z",
            "generatorURL": "https://example.com/graph#..."
        }
    ],
    "groupLabels": {
        "alertname": "something_happend",
        "instance": "server01.int:9100"
    },
    "commonLabels": {
        "alertname": "something_happend",
        "env": "prod",
        "instance": "server01.int:9100",
        "job": "node",
        "service": "prometheus_bot",
        "severity": "warning",
        "supervisor": "runit"
    },
    "commonAnnotations": {
        "summary": "runit service prometheus_bot restarted, server01.int:9100"
    },
    "externalURL": "https://alert-manager.example.com",
    "version": "3"
}' http://prometheus-webhook-dingtalk:30595/dingtalk/webhook1/send
404 page not found

**Comment by timonwong** [comment]
404 page not found 一般是 profile 定义有问题，请列出 `args`

**Comment by Ghostbaby** [comment]
非常感谢回复，问题就是引号的，已经解决了。
谢谢贡献。
