### ISSUE TITLE
想请问下日志文件在哪儿？

### ISSUE THREAD

**Issue by 7A6A78** [timonwong/prometheus-webhook-dingtalk#181]
看到参数里能配置日志等级和格式，但是找了半天没找到日志文件，是还不支持日志文件单独存放吗？

**Comment by timonwong** [comment]
没有日志文件，只输出 stderr

**Comment by 7A6A78** [comment]
想问下没有日志文件，是基于什么考虑呢？



在 2022-04-21 14:29:55，"Timon Wong" ***@***.***> 写道：

没有日志文件，只输出 stderr

**Comment by timonwong** [comment]
如上所述，有 systemd, systemd 可以管理日志，跑在容器环境，容器帮你管理日志。有 supervisor, monit 等工具，也能帮你归类日志（rotate, zip, etc)，没有必要单独处理。

非得需要也可以自己重定向然后处理日志文件。
