### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by neb0t** [timonwong/prometheus-webhook-dingtalk#182]
Hello @timonwong ,
I see you are using latest busybox as from build image for docker image. 
Could you please release a new version with the latest busybox image?
The old one has some vulnerability issues and it would be much easier to ask you to release new patch version rather than do a fork and release the same image under my name.

**Comment by timonwong** [comment]
Since v2.1.0 the base image is now replaced with distroless/static

**Comment by neb0t** [comment]
Thanks for update!
By the way, I don’t see new docker image. Are you going to release v2.1.0 or should I use version from main ?

---

Best regards,
Maksym Nebot

**Comment by timonwong** [comment]
@neb0t  The latest docker image is `timonwong/prometheus-webhook-dingtalk:v2.1.0`

**Comment by neb0t** [comment]
Thank you @timonwong!
