### ISSUE TITLE
怎么获取 故障持续时间

### ISSUE THREAD

**Issue by lss144** [timonwong/prometheus-webhook-dingtalk#194]
如题 请问怎么在template里获取故障持续时间 @timonwong

**Comment by Spinestars** [comment]
{{ define "my.__text_firing_list" }}{{ range . }}
    **报警时间:** {{ dateInZone "2006.01.02 15:04:05" (.StartsAt) "Asia/Shanghai" }}
    {{ template "my.__text_alert_list" . }}
    {{ end }}{{ end }}

    {{ define "my.__text_resolved_list" }}{{ range . }}
    **持续时间:** {{ dateInZone "2006.01.02 15:04:05" (.StartsAt) "Asia/Shanghai" }} to {{ dateInZone "2006.01.02 15:04:05" (.EndsAt) "Asia/Shanghai" }}
    {{ template "my.__text_alert_list" . }}
    {{ end }}{{ end }}
