### ISSUE TITLE
"errcode":310000,"errmsg":"keywords not in content

### ISSUE THREAD

**Issue by zpike** [timonwong/prometheus-webhook-dingtalk#197]
curl -H "Content-Type: application/json" -d '{"msgtype":"text","text":{"content":"prometheus alert test"}}' https://oapi.dingtalk.com/robot/send?access_token=0c23

测试的 keyword是?

**Comment by timonwong** [comment]
机器人安全设置请使用 IP 地址或者加签。

**Comment by timonwong** [comment]
加签参照实例配置添加/修改 secret 字段: `secret: SECXXXXXXXXXXXXXXXXXXXX`
