### ISSUE TITLE
关于模版中GeneratorURL的定义

### ISSUE THREAD

**Issue by Ghostbaby** [timonwong/prometheus-webhook-dingtalk#20]
项目中目前模版发送出来的告警，其中source中的链接是k8s svc的名称，我需要修改成ingress的外网域名。请问大佬如何修改。
`[FIRING:1] something_happend server01.int:9100 (prod node prometheus_bot warning runit)
#### \[FIRING:1\] **[something_happend](https://alert-manager.example.com/#/alerts?receiver=admins)**

**Labels**
> - alertname: something\_happend
> - env: prod
> - instance: server01.int:9100
> - job: node
> - service: prometheus\_bot
> - severity: warning
> - supervisor: runit

**Annotations**
> - summary: Oops, something happend!

**Source:** ["Link"]**(https://example.com/graph#...)**`

**Comment by timonwong** [comment]
我建议你先看看 prometheus 的 command line flags:

`--web.external-url`

> The URL under which Prometheus is externally reachable (for example, if Prometheus is served via a reverse proxy). Used for generating relative and absolute links back to Prometheus itself. If the URL has a path portion, it will be used to prefix all HTTP endpoints served by Prometheus. If omitted, relevant URL components will be derived automatically.

别什么问题都往这个项目里面提 issue，再这样下去这里就会变成钉钉、prometheus 以及 prometheus alertmanager 的中文讨论区了。

**Comment by bwcxyk** [comment]
![image](https://user-images.githubusercontent.com/28802427/72237593-fd4b3900-3615-11ea-8a06-a28dfadde8ad.png)
恢复的url还是主机名，怎么解

**Comment by NoviceZeng** [comment]
[FIRING:1] 主机状态，这个主机状态所在的链接好像不是通过--web.external-url来改的，请问从哪里改呢
