### ISSUE TITLE
请问代码里面可以对告警时间做格式化处理吗？

### ISSUE THREAD

**Issue by StandNorthStar** [timonwong/prometheus-webhook-dingtalk#24]
作者你好，我想对告警时显示时间格式为(yyyy-mm-dd HH:mm:ss) 但是我没有查找到template这样的设置。 另外恢复时怎么计算告警持续的时间？ 我想在模板里面做下数学运算，但是没找是否可以这样做。
这个是我把时间换成时间戳{{ .EndsAt.Unix }} - {{ .StartsAt.Unix }} ，不过不晓得咋运算。 
作者可以添加这两个小更能否？ （wo不懂go）

**Comment by timonwong** [comment]
1. `{{ .StartsAt.Format "2006-01-02 15:04:05" }}`   See: https://golang.org/pkg/time/#pkg-constants   多了解下 golang 吧
2.不支持数学运算，你只是想看持续时间，用 `{{ .EndsAt.Sub .StartsAt }}` 就可以了

**Comment by timonwong** [comment]
1.0.0 里面模板引入了 [sprig](http://masterminds.github.io/sprig) ，应该更简单一些了:

http://masterminds.github.io/sprig/date.html
