### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by CaoZhenggg** [timonwong/prometheus-webhook-dingtalk#26]
你好，make编译报错

[root@service01-ali_hz:/opt/prometheus-webhook-dingtalk → master]# make
>> formatting code
>> building binaries
> prometheus-webhook-dingtalk
can't load package: package github.com/timonwong/promet... cannot find package "github.com/timonwong/promet..." in any of:
/opt/golang/src/github.com/timonwong/promet... (from $GOROOT)
/root/go/src/github.com/timonwong/promet... (from $GOPATH)
!! command failed: build -o /opt/prometheus-webhook-dingtalk/prometheus-webhook-dingtalk -ldflags -s -X github.com/timonwong/promet... -X github.com/timonwong/promet... -X github.com/timonwong/promet... -X github.com/timonwong/promet... -X github.com/timonwong/promet... -extldflags '-static' -a -tags 'netgo static_build' github.com/timonwong/promet... exit status 1
make: *** [build] Error 1

**Comment by tccod** [comment]
Try compiling with the latest version of golang. Issue resolved with the latest version.

**Comment by timonwong** [comment]
你需要了解一下 Golang 的 workspace, $GOPATH
简单的说，这个项目要放到 $GOPATH/src/github.com/timonwong/prometheus-webhook-dingtalk 才能进行编译

https://github.com/golang/go/wiki/GOPATH
https://golang.org/doc/code.html#Workspaces
