### ISSUE TITLE
关于模板中链接的问题

### ISSUE THREAD

**Issue by redpangzi666** [timonwong/prometheus-webhook-dingtalk#27]
您好，我使用了默认模板，发现标题的链接不是我想要的，能否将详情的超链接做成 `title_link` 这种形式？而且 `source` 中的超链接访问模式是`http`,正确的模式应该是 `https`，请问这个应该如何修改

**Comment by timonwong** [comment]
1. 不懂你的意思。不过你只要了解 [golang template](https://golang.org/pkg/text/template) ，这个是你自己就能改的
2. See #20

**Comment by yuge994** [comment]
这个是在你prometheus里面设置的   启动prometheus的时候加一条配置        
 --web.external-url=https://example.com/prometheus/

**Comment by xujingbin** [comment]
> 这个是在你prometheus里面设置的 启动prometheus的时候加一条配置
> --web.external-url=https://example.com/prometheus/

prometheus-webhook-dingtalk: error: unknown long flag '--web.external-url', try --help

**Comment by yuge994** [comment]
> > 这个是在你prometheus里面设置的 启动prometheus的时候加一条配置
> > --web.external-url=https://example.com/prometheus/
> 
> prometheus-webhook-dingtalk: error: unknown long flag '--web.external-url', try --help

是你prometheus启动的时候加的参数  不是prometheus-webhook-dingtalk

**Comment by xujingbin** [comment]
好的 谢谢

**Comment by xujingbin** [comment]
> > > 这个是在你prometheus里面设置的 启动prometheus的时候加一条配置
> > > --web.external-url=https://example.com/prometheus/
> > 
> > 
> > prometheus-webhook-dingtalk: error: unknown long flag '--web.external-url', try --help
> 
> 是你prometheus启动的时候加的参数 不是prometheus-webhook-dingtalk

![image](https://user-images.githubusercontent.com/22829724/72337794-1f1feb00-36fe-11ea-84ac-34938f6852f1.png)
两个报警 恢复一个后，发送的信息还是两个都是报警状态，这是bug吗

**Comment by yuge994** [comment]
> > > > 这个是在你prometheus里面设置的 启动prometheus的时候加一条配置
> > > > --web.external-url=https://example.com/prometheus/
> > > 
> > > 
> > > prometheus-webhook-dingtalk: error: unknown long flag '--web.external-url', try --help
> > 
> > 
> > 是你prometheus启动的时候加的参数 不是prometheus-webhook-dingtalk
> 
> ![image](https://user-images.githubusercontent.com/22829724/72337794-1f1feb00-36fe-11ea-84ac-34938f6852f1.png)
> 两个报警 恢复一个后，发送的信息还是两个都是报警状态，这是bug吗

这个得找作者了

**Comment by xujingbin** [comment]
![image](https://user-images.githubusercontent.com/22829724/72341847-42e72f00-3706-11ea-8558-810615fdb5e7.png)
我明白了，是模板那边循环的问题，加上默认的才正常

**Comment by zhangkangyue** [comment]
> > 这个是在你prometheus里面设置的 启动prometheus的时候加一条配置
> > --web.external-url=https://example.com/prometheus/
> 
> prometheus-webhook-dingtalk: error: unknown long flag '--web.external-url', try --help

想在告警信息模板中，加一个链接项：用于被告警人点击交互，可以通过在配置文件里配置吗？
如恢复告警:www.XXXX.YYY

**Comment by xujingbin** [comment]
点击交互是做什么用的？ 我这里只配置了可以点击告警链接，进入查看详情
想着可以直接点击静默告警的，还没时间研究
