### ISSUE TITLE
没有钉某人的选项吗？

### ISSUE THREAD

**Issue by w568590301** [timonwong/prometheus-webhook-dingtalk#33]

**Comment by fangjianfeng** [comment]
已经解决，https://github.com/timonwong/prometheus-webhook-dingtalk/pull/35/commits/17929b654fa52fc8e67b57b9b324d9d274c1f41a

**Comment by timonwong** [comment]
感谢 @fangjianfeng , 修改后已经合并进主分支，并发布 1.0.0

#54

**Comment by Notmeor** [comment]
这是 @ , 并不是 ding .
