### ISSUE TITLE
手机钉钉显示的比 pc钉钉显示少

### ISSUE THREAD

**Issue by muzigan** [timonwong/prometheus-webhook-dingtalk#34]
![image](https://user-images.githubusercontent.com/43438842/57189239-8619bd00-6f3e-11e9-8c44-684966e904b9.png)
![image](https://user-images.githubusercontent.com/43438842/57189250-ab0e3000-6f3e-11e9-9695-ef373e98225d.png)

我的 template文件如下：
**Labels**
{{ range .Labels.SortedPairs }}
{{ if eq .Name "alertname" }}> [报警名称]: {{ .Value | markdown | html }}{{ end }}
{{ if eq .Name "instance" }}> [主机]: {{ .Value | markdown | html }}{{ end }}
{{ if eq .Name "device" }}> [网卡名]: {{ .Value | markdown | html }}{{ end }}
{{ end }}
**Annotations**
{{ range .Annotations.SortedPairs }}
{{ if eq .Name "description" }}> [描述]: {{ .Value | markdown | html }}{{ end }}
{{ end }}

{{ end }}{{ end }}

**Comment by scottyungit** [comment]
请问怎么解决的？
