### ISSUE TITLE
时区问题

### ISSUE THREAD

**Issue by NaturAlex** [timonwong/prometheus-webhook-dingtalk#37]
我 的dingtalk日志  alterManager日志 还有prometheus的管理页面输出的时间都是非东8区时间,
系统命令date输出的命令时间没错 date -R也没错  grafana的时间也是正确的,请指导下~谢谢

**Comment by timonwong** [comment]
时区只支持 UTC: 
https://prometheus.io/docs/introduction/faq/#can-i-change-the-timezone-why-is-everything-in-utc
