### ISSUE TITLE
关于模板文件中新加一些指标如何实现。

### ISSUE THREAD

**Issue by azure-sea** [timonwong/prometheus-webhook-dingtalk#39]
你好, 我想在模板文件中添加告警时间 与 告警持续时间,  我通过查看该问题https://github.com/timonwong/prometheus-webhook-dingtalk/issues/24
简单修改了一下默认模板配置。

```
{{ define "__text_alert_list" }}{{ range . }}
**Time**
{{ .StartsAt.Format "2006-01-02 15:04:05" }}  \n
**Labels**
{{ range .Labels.SortedPairs }}> - {{ .Name }}: {{ .Value | markdown | html }}
{{ end }}
**Annotations**
{{ range .Annotations.SortedPairs }}> - {{ .Name }}: {{ .Value | markdown | html }}
{{ end }}
**Source:** [{{ .GeneratorURL }}]({{ .GeneratorURL }})

{{ .EndsAt.Sub .StartsAt }}

{{ end }}{{ end }}
```

**Comment by azure-sea** [comment]
但是告警通知的输出与我想要的不相符，时间没有换行，持续时间没有格式化
![123123](https://user-images.githubusercontent.com/44580994/66375845-eeceff00-e9e0-11e9-9fa4-ef9f3e7a80c8.png)

**Comment by timonwong** [comment]
v1.2.0 新增了 web ui，希望能帮到

https://github.com/timonwong/prometheus-webhook-dingtalk/blob/master/docs/FAQ_zh.md
