### ISSUE TITLE
Code422是什么状态？

### ISSUE THREAD

**Issue by hongdi1992** [timonwong/prometheus-webhook-dingtalk#40]
dingtalk已经配置很多项目了，今天配置新项目的时候，总是报
Failed to send notification to DingTalk respCode=300001 respMsg="message param text is null"
http_scheme=http_proto=HTTP/1.1 http_method=PST remote_addr=[::1]:40784 user_agent=Alertmanager/0.15.3 uri=http://localhost:8141/dingtalk/ops_dingding/send resp_status=422 resp_bytes_length=27 resesp_elasped_ms=58.143594 msg="request complete"

alertmanger里也有相关状态422的报错，请问这个422是什么问题？

**Comment by timonwong** [comment]
这个属于消息格式问题，简单的说就是这个 webhook 发送到钉钉的消息被拒收了（因为格式错误）。这是改过代码吧？http_method 应该是 POST 的
