### ISSUE TITLE
钉钉webhook加入安全认证，新建机器人无法使用

### ISSUE THREAD

**Issue by ytc301** [timonwong/prometheus-webhook-dingtalk#41]
钉钉webhook加入安全认证，这个告警什么时候更新支持，不然钉钉新建的机器人无法推送信息

**Comment by tianjun1990** [comment]
没人维护了吗？ 这个头疼

**Comment by gerrard2030** [comment]
安全认证，去钉钉群-机器人-自己选根据label还是IP， 跟这个插件没关系，目前我可以正常使用。

**Comment by timonwong** [comment]
The lastest master branch should address this problem
