### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by w564791** [timonwong/prometheus-webhook-dingtalk#5]
HI 我在K8S里面使用这个，但是post的时候都是404  开了debug模式。但是好像没有输出，我尝试用curl手动POST数据到webhook1,也是返回的404,请问可能十哪儿出现在了问题呢

**Comment by w564791** [comment]
我试了在K8S里面跑起来就会404  但是单独run的话  就没有问题。

**Comment by timonwong** [comment]
直接运行是 docker 执行的还是用的二进制？
下个版本我会打一个 request log，帮助排查问题
#6

**Comment by w564791** [comment]
Hi  我找到问题了哈  部署在K8S里面,使用args的时候不能加引号,加了引号就会触发这个问题.问题已经解决了哦  万分感谢

**Comment by w564791** [comment]
另外source那儿链接  能不能设定成超链接 ,,source的网址太长了  不好看

**Comment by zmm2016** [comment]
小白请教如何在k8s中安装部署？@w564791，能否给个教程什么的？

**Comment by w564791** [comment]
作者有现成的镜像，可以直接用

在 2017年12月21日，上午11:49，zmm2016 <notifications@github.com<mailto:notifications@github.com>> 写道：


小白请教如何在k8s中安装部署？@w564791<https://github.com/w564791>，能否给个教程什么的？

**Comment by zmm2016** [comment]
感谢作者以及仁兄的解答，我在docker中跑通了

**Comment by timonwong** [comment]
> 另外source那儿链接 能不能设定成超链接 ,,source的网址太长了 不好看

@w564791 我个人还是倾向于使用完整链接，方便纯文本的复制粘贴。不过以后我会提供模板的定制功能以满足你的需求。

**Comment by w564791** [comment]
万分感谢

在 2017年12月21日，下午2:07，Timon Wong <notifications@github.com<mailto:notifications@github.com>> 写道：


另外source那儿链接 能不能设定成超链接 ,,source的网址太长了 不好看

@w564791<https://github.com/w564791> 我个人还是倾向于使用完整链接，方便纯文本的复制粘贴。不过以后我会提供模板的定制功能以满足你的需求。

**Comment by timonwong** [comment]
See #7

**Comment by timonwong** [comment]
0.3.0 发布了，你可以试试，  这个 issue 我先关了

**Comment by Accpet** [comment]
为啥 我问题还存在？？

**Comment by Accpet** [comment]
[root@grafana alertmanager]#   curl http://localhost:8060/dingtalk/web.hook/send \
>    -H 'Content-Type: application/json' \
>    -d '{"msgtype": "text",
>         "text": {
>              "content": "我就是我, 是不一样的烟火"
>         }
>       }'
404 page not found

**Comment by kl13579y** [comment]
> [root@grafana alertmanager]# curl http://localhost:8060/dingtalk/web.hook/send \
> 
> > -H 'Content-Type: application/json' 
> > -d '{"msgtype": "text",
> > "text": {
> > "content": "我就是我, 是不一样的烟火"
> > }
> > }'
> > 404 page not found

链接中的 web.hook 要对应 参数 ding.profile 中的名字，检查下 web.hook 的名字是不是其他的名字
比如  http://localhost:8060/dingtalk/test.web.hook/send
