### ISSUE TITLE
从 v0.3.0 升级后, 命令行参数不兼容, 无法启动程序

### ISSUE THREAD

**Issue by CasperLiu** [timonwong/prometheus-webhook-dingtalk#64]

**Comment by CasperLiu** [comment]
使用lastest tag的image目前无法启动，持续CrashLoopback。
目前有不少alertmanager对接钉钉使用该开源软件，希望尽快修复。
而且以后开发建议使用单独的测试tag，而不用到latest，等测试通过再打上latest。
谢谢！

**Comment by timonwong** [comment]
请不要使用 latest tag, BREAKING CHANGE 请看 changelog

**Comment by timonwong** [comment]
CHANGES:
- https://github.com/timonwong/prometheus-webhook-dingtalk/releases
- https://github.com/timonwong/prometheus-webhook-dingtalk/blob/master/CHANGELOG.md
- https://github.com/timonwong/prometheus-webhook-dingtalk/blob/master/docs/FAQ_zh.md

如果不想改为配置文件, 保持使用 v0.3.0

**Comment by timonwong** [comment]
经过一番考虑，决定加入兼容模式支持 v0.3.0 的命令行参数 #72

**Comment by timonwong** [comment]
v1.3.0 已发布，支持 v0.3.0 的命令行参数
