### ISSUE TITLE
docker image the code dir is empty

### ISSUE THREAD

**Issue by boldmanQ** [timonwong/prometheus-webhook-dingtalk#69]
_$ docker exec -ti prometheus-webhook-dingtalk /bin/sh
/prometheus-webhook-dingtalk $ ls
/prometheus-webhook-dingtalk $ ls -al
total 0
drwxr-xr-x    2 nobody   nogroup          6 Dec  9 01:16 .
drwxr-xr-x    1 root     root           109 Dec  9 09:09 ..
/prometheus-webhook-dingtalk $ ls -al
total 0
drwxr-xr-x    2 nobody   nogroup          6 Dec  9 01:16 .
drwxr-xr-x    1 root     root           109 Dec  9 09:09 ..
/prometheus-webhook-dingtalk $_

**Comment by timonwong** [comment]
Yeah, it's intended to store user files (such as config), since it's the default working dir.

https://github.com/timonwong/prometheus-webhook-dingtalk/blob/master/Dockerfile

**Comment by timonwong** [comment]
I'm closing this issue, if there is any problem then just reopen it.

**Comment by boldmanQ** [comment]
Yes, i know how to make it work
