### ISSUE TITLE
还是模板问题

### ISSUE THREAD

**Issue by successfuljian** [timonwong/prometheus-webhook-dingtalk#79]
首先感谢您分享webhook-dingtalk

我把加载模板已经成功加载自定义模板了   可是发现还是没有用自定义的 还是走的封装到代码里的default.tmpl啊 

![image](https://user-images.githubusercontent.com/7867667/71158145-5f668780-227e-11ea-9cdf-da162af9eef3.png)

**Comment by successfuljian** [comment]
这是我的自定义我只是尝试改了 几个值  
![image](https://user-images.githubusercontent.com/7867667/71158247-8fae2600-227e-11ea-806e-9dce5d79f45b.png)

**Comment by timonwong** [comment]
您好，我查了一下您所使用的程序源码是被修改过的，可能是中间修改出了问题。
请尽量使用发布的版本: https://github.com/timonwong/prometheus-webhook-dingtalk/releases


**Comment by KeithTt** [comment]
@timonwong 可以禁用 markdown 么？改半天都不按路数来
