### ISSUE TITLE
如何配置将信息精简

### ISSUE THREAD

**Issue by zmm2016** [timonwong/prometheus-webhook-dingtalk#8]
首先感谢分享，现在已经用docker部署好了环境并且可以正常发送钉钉消息，但是钉钉消息罗列在一起显得非常臃肿，请问怎么能够配置提供简单提示的标题，详细内容可通过点击进入后查看。我想定制化发送信息的方式的话怎么去配置修改呢？重写template.file？

**Comment by timonwong** [comment]
嗯，自定义 template.file 就可以了，语法是 [go template](https://golang.org/pkg/text/template/)，使用了部分 Markdown

这是一个简化的例子，将 `Source` 一节直接做成超链接:
```
{{ define "__subject" }}[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.SortedPairs.Values | join " " }} {{ if gt (len .CommonLabels) (len .GroupLabels) }}({{ with .CommonLabels.Remove .GroupLabels.Names }}{{ .Values | join " " }}{{ end }}){{ end }}{{ end }}
{{ define "__alertmanagerURL" }}{{ .ExternalURL }}/#/alerts?receiver={{ .Receiver }}{{ end }}

{{ define "__text_alert_list" }}{{ range . }}
**Labels**
{{ range .Labels.SortedPairs }}> - {{ .Name }}: {{ .Value | markdown | html }}
{{ end }}
**Annotations**
{{ range .Annotations.SortedPairs }}> - {{ .Name }}: {{ .Value | markdown | html }}
{{ end }}
[Source]({{ .GeneratorURL }})

{{ end }}{{ end }}

{{ define "ding.link.title" }}{{ template "__subject" . }}{{ end }}
{{ define "ding.link.content" }}#### \[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}\] **[{{ index .GroupLabels "alertname" }}]({{ template "__alertmanagerURL" . }})**
{{ template "__text_alert_list" .Alerts.Firing }}
{{ end }}
```
你可以跟默认模板比较一下：https://github.com/timonwong/prometheus-webhook-dingtalk/blob/d04cd50b81e76af555fdb108a559a8a432a8dc4e/template/default.tmpl

另外，因为 template.file 是指向的文件，推荐你先在本地测通之后，再上到 docker 上

**Comment by zmm2016** [comment]
本地docker已经布好了，怎么通过命令行来修改部好示例呢？

**Comment by zmm2016** [comment]
我的意思是怎么通过命令行去修改默认的模板？prometheus-webhook-dingtalk的docker实例内部可以修改吗？还是通过docker run 的时候 --template.file=""配置，我没有尝试成功？

**Comment by timonwong** [comment]
你有两个选择:
- 使用 volume mount, 如果是 k8s，用 `configMap` 
- 新做一个镜像，加入你的 template 文件

**Comment by zmm2016** [comment]
-v /Users/prometheus/ding.tmpl:/usr/share/prometheus-webhook-dingtalk/template/default.tmpl 

通过命令配置后还是以前的tmpl发送信息，并没有根据新的模板形式来发送

**Comment by timonwong** [comment]
你需要加上 `--template.file` 参数来指定模板文件的地址，成功后，日志里面会这样输出:
```
level=info ts=2018-01-08T13:01:15.826457026Z caller=main.go:55 filename=template/custom.tmpl msg="Using customized template"
```

**Comment by zmm2016** [comment]
docker run 起的镜像timonwong/prometheus-webhook-dingtalk 
输入命令：prometheus-webhook-dingtalk -h
显示：
usage: prometheus-webhook-dingtalk --ding.profile=DING.PROFILE [<flags>]
Flags:
  -h, --help             Show context-sensitive help (also try --help-long and --help-man).
      --web.listen-address=":8060"
                         The address to listen on for web interface.
      --ding.profile=DING.PROFILE ...
                         Custom DingTalk profile (can specify multiple times, <profile>=<dingtalk-url>).
      --ding.timeout=5s  Timeout for invoking DingTalk webhook.
      --log.level=info   Only log messages with the given severity or above. One of: [debug, info, warn, error]
      --version          Show application version.


并没有--template.file
执行 prometheus-webhook-dingtalk --template.file=/etc/alertmanager/template/tradeemail.tmpl
prometheus-webhook-dingtalk: error: unknown long flag '--template.file', try --help

**Comment by timonwong** [comment]
你没有用最新的，最新的是 `0.3.0`
