### ISSUE TITLE
想在firing的信息里加红色，resolved里加绿色可以吗

### ISSUE THREAD

**Issue by xujingbin** [timonwong/prometheus-webhook-dingtalk#82]
想在firing的信息里加红色，resolved里加绿色可以吗

mardown上可以加，但是模板里不行

**Comment by timonwong** [comment]
dingding的markdown不支持

**Comment by xujingbin** [comment]
![image](https://user-images.githubusercontent.com/22829724/72345249-2e0e9980-370e-11ea-9e92-9f66704360b3.png)
可以支持吗？  像这样就好看多了

**Comment by timonwong** [comment]
钉钉本身就不支持，所以除非钉钉支持才行

**Comment by xujingbin** [comment]
@timonwong <font color=#FF0000 size=8 face="黑体">Alerts Firing</font>
这样就支持颜色咯

**Comment by xujingbin** [comment]
@timonwong 这样就支持颜色哦
’<font color=#FF0000 size=8 face="黑体">触发规则</font>‘

**Comment by xujingbin** [comment]
@timonwong 这样可以支持颜色哦
![image](https://user-images.githubusercontent.com/22829724/72703038-8111a200-3b8f-11ea-92c5-48d5df54df12.png)
