### ISSUE TITLE
msg="target not found"

### ISSUE THREAD

**Issue by iuwai** [timonwong/prometheus-webhook-dingtalk#88]
### 报错：
`level=warn ts=2020-03-18T03:01:29.787Z caller=dingtalk.go:75 component=web target=webhook1 msg="target not found"`
### config.yml配置：
 timeout: 5s

 templates:
   - contrib/templates/legacy/template.tmpl

 default_message:
   title: '{{ template "legacy.title" . }}'
   text: '{{ template "legacy.content" . }}'

targets:
  webhook1:
    url: https://oapi.dingtalk.com/robot/send?access_token=

**Comment by timonwong** [comment]
通常在于启动参数指定了错误的配置，你可以仔细看看启动日志，里面会列出有效的「targets」

**Comment by timonwong** [comment]
![image](https://user-images.githubusercontent.com/1398228/76925197-939c2380-6913-11ea-95c9-60162e5eb00c.png)
