### ISSUE TITLE
template 不生效

### ISSUE THREAD

**Issue by baiyibing123** [timonwong/prometheus-webhook-dingtalk#90]
昨天改的模板本来已经生效了，莫名又不好使了
![image](https://user-images.githubusercontent.com/14048464/77067302-b582cc80-6a1f-11ea-8eb1-2d885a62b439.png)
很奇怪，本来好好的

修改了template.tmpl
并在config.yml里指定了templates
好像还必须添加
    message:
      title: '{{ template "legacy.title" . }}'
      text: '{{ template "legacy.content" . }}'
否则用的还是默认的模板
但是现在报错了

**Comment by baiyibing123** [comment]
找到问题了，是因为我在模板里加了一句话
**告警数值:** {{ .value }}
导致了模板不能用，这是为什么呢，那我因为怎么引用告警里的实际数值呢

**Comment by baiyibing123** [comment]
另外我定义了发告警的模板，我的RESOLVED应该如何定义呢，RESOLVED的时候也想引用发告警的模板

**Comment by baiyibing123** [comment]
`{{/* Default */}}
{{ define "default.title" }}{{ template "__subject" . }}{{ end }}
{{ define "default.content" }}#### \[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}\] **[{{ index .GroupLabels "alertname" }}]({{ template "__alertmanagerURL" . }})**
{{ if gt (len .Alerts.Firing) 0 -}}
**Alerts Firing**
{{ template "default.__text_alert_list" .Alerts.Firing }}
{{- end }}
{{ if gt (len .Alerts.Resolved) 0 -}}
**Alerts Resolved**
{{ template "default.__text_alert_list" .Alerts.Resolved }}
{{- end }}
{{- end }}

{{/* Legacy */}}
{{ define "legacy.title" }}{{ template "__subject" . }}{{ end }}
{{ define "legacy.content" }}#### \[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}\] **[{{ index .GroupLabels "alertname" }}]({{ template "__alertmanagerURL" . }})**
{{ template "__text_alert_list" .Alerts.Firing }}
{{- end }}

{{/* Following names for compatibility */}}
{{ define "ding.link.title" }}{{ template "default.title" . }}{{ end }}
{{ define "ding.link.content" }}{{ template "default.content" . }}{{ end }}`

**Comment by KeithTt** [comment]
请教一下楼主，这个模板要怎么写？能使用哪些变量？这个项目里面有文档提到么？
