### ISSUE TITLE
钉钉机器人现在除了token以外，还需要加签，这个支持吗

### ISSUE THREAD

**Issue by liuhaibo0303** [timonwong/prometheus-webhook-dingtalk#94]
现在的钉钉机器人，必须选择一种安全方式，目前加签是最好的方式
![image](https://user-images.githubusercontent.com/32126569/79200821-9d10a100-7e69-11ea-8dd8-95c801a523f4.png)

**Comment by timonwong** [comment]
支持，看配置例子:
https://github.com/timonwong/prometheus-webhook-dingtalk#configuration
