### ISSUE TITLE
请问prometheus-webhook-dingtalk能否跳过安全证书

### ISSUE THREAD

**Issue by wuyachun91** [timonwong/prometheus-webhook-dingtalk#95]
钉钉机器人的地址报certificate has expired or is not yet valid。
手动用curl测试需要加上-k参数才可调通。

**Comment by wuyachun91** [comment]
对于这种生产环境的场景，prometheus-webhook-dingtalk有方法规避解决吗？谢谢

**Comment by timonwong** [comment]
https://github.com/timonwong/prometheus-webhook-dingtalk/blob/master/README.md#configuration

配置文件

发自我的iPhone

**Comment by timonwong** [comment]
sorry 我再确认下 回复错了

发自我的iPhone

**Comment by timonwong** [comment]
您好，我看了你的问题，因为本身此插件并不提供 https，如果你需要 HTTPS，请自行在前面挂 reverse proxy 比如 nginx
